"""Make category name unique

Revision ID: 7a37120dd47e
Revises: dc6c1e775450
Create Date: 2020-11-27 17:56:44.793544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a37120dd47e'
down_revision = 'dc6c1e775450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'mcc_category', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mcc_category', type_='unique')
    # ### end Alembic commands ###
